# Generated by Django 5.0.6 on 2024-06-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_signup_rename_name_user_login_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'FeMale')])),
                ('birthdate', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='user_login',
        ),
        migrations.DeleteModel(
            name='user_signup',
        ),
    ]
